dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codacy-coverage
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- coverage run --branch --source=. ./manage.py test mixnet --keepdb
- coverage xml
- python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: egc-app-decide-joscorfis
  strategy: git
  api_key:
    secure: XSz+hhwiIx6EtNa1B+fk85wMwXk1nWM3TBfPQrf7SUWjZjxXMDkK9tdN8usfav6M1O0U322CUX0yNZtM1ioJ6dov+5xosl8ADMiU8BogNqIRm+5IusOWyfWD0KvNFXq+M85smrIgDwSmXpv2vuJKmZ1F+tQEcfp0eMhrE5V6Gd1tpcYVySevkTO/rzJesBpUGBNPL1lcv2ldVXz5YDyZAyBBMPbl9mJenXNH+Z53GxUILloBrKBjXcC43I8kQEphCsTBVp924rKQ9cLQOJyXK5EwdTmtQ3IJ5ayS5vn9KFcXeXGUfSmiFts0+CsOvedF6sbd45VdY75oD2dLksjRGxzVlejiUqRF7ie1NHDjQ8AHmRDbwDtZTkBxLWSWx2pP48BrUZDCchm60Wo0wObl5kueVJ9pVJkTyL0c7tflmK+UydaNrFV08Lha0sGDdys6F9nx+8Hlq1o1VXC9/2yMvE8uis57yg7Td7Bj4/if8ttsNd2R0qlWv6s4nCiFq3L+HaQUEZKR3tKOnSKDZXuLeKHEVS41DJwH3lsLqOwzvKENNbPGWBtEuUZs/u0CbRXLsomIF6r3ZMhgcPDUZLakqRphzIQCUIyTxOe8q6YihDpWrXD4elVYDgW64bRhhedAVor77lQwkoeKRlp5Ki9IMs547vBfyW45SY2049+A44s=
